module.exports = {
    GET_STAFF_REQUEST: "app/GET_STAFF_REQUEST",
    ADD_STAFF_REQUEST: "app/ADD_STAFF_REQUEST",
    DELETE_STAFF_REQUEST: "app/DELETE_STAFF_REQUEST",
    EDIT_STAFF_REQUEST: "app/EDIT_STAFF_REQUEST",
    ADD_TIME_REQUEST: "app/ADD_TIME_REQUEST",
}